oaubert/python-vlc

generator/templates/footer.py
Added `-v` and `--version` command line option to print `vlc.py`, `libvlc`, Python and O/S versions.  Needs the `distro` package to get Linux distribution details.  If `distro` is not installed, just shows `Linux` .
=> Enhanced footer.py

Makefile, generator/templates/header.py
Hello,
This small patch adds support for FreeBSD. It passes the tests as shown in the log: [test.log](https://github.com/oaubert/python-vlc/files/2897898/test.log).
Thank you for considering it.
Hukadan
=> Adding FreeBSD support.

examples/tkvlc.py
This `tkvlc.py` example works and looks a lot better now on macOS, like a proper macOS application.
The menu items and shortcut keys all work and compensate for the buttons hidden under the video.
The `Play` menu, button and `P` shortcut key toggle between Play and Pause, the `Mute` menu, button and `M` shortcut key toggle between Mute and Unmute.
The `Quit` menu, the `Q`  and `W` shortcut keys and the error dialog are all working now without errors.
The `Full Screen` menu item and `F` shortcut have been added and behave like other macOS applications, including the `Escape` key to switch back.
The `threading`-based timer class has been replaced by a one-line call to Tk's `after` method.
Still unresolved remain these 2 issues:
- The buttons and sliders in the main window are overwritten by …
=> Final tkvlc.py updates.

examples/wxvlc.py
Made 3 updates to use `wxPython` 4.0.6: `wxFD_OPEN`, `timer.Start(1000)` and `wx.App()`.
Renamed the `Volume` button to toggle between `Mute` and `Unmute`.
Enable and disable the `Play`, `Pause` and `Stop` button to avoid error message from VLC.
Tested _only with_ wxPython 4.0.6, wxWidgets 3.0.5 and Python 3.7.4 64-bit on macOS 10.13.6, see screen shot.
=> Updated wxvlc.py to wxPython 4.0.6.

examples/pyobjcvlc.py
This is another, simple VLC media player `for macOS only`, this one based on [PyObjC](https://PyPI.org/project/PyObjC).
It has been tested with Python 2.7.10 and PyObjC 2.5.1 (both included with macOS) and with Python 3.7.4 and the latest PyObjC 5.2b1, both in 64-bit only on macOS 10.13.6 High Sierra.  More details at the top of the file.
Travis CI testing of `pyobjcvlc.py` is similar to `cocoavlc.py`, i.e. only on macOS if possible.
=> Another example pyobjcvlc.py

generator/templates/header.py
This fixes the dll import issues in windows when running from a pyinstaller executable.
=> Fix PyInstaller Windows dll import issue

generator/generate.py, tests/test.py
Close #117 
As per discussion in the issue, I tried to improve a bit the parser for parameters. It is far from being perfect.
The new method should is not regex based, it should be able to detect all types and pointers with related constness. The constness information is stored inside `Par` as a list of bools, intrinsically giving two information:
- it is a value (`len==0`), a pointer (`len==1`) or a pointer to pointer (`len==2`)
- constness for each existing level of indirection
e.g.
- `const int *` -> `[True, False]`
- `const int * const` -> `[True, True]`
- `int * const` -> `[False, True]`
=> Improve parameters parsing and fix callbacks

generator/templates/header.py
Closes #118 
Since Python 3.8, dll files cannot be loaded anymore from name only.
From https://docs.python.org/3/whatsnew/3.8.html :
> DLL dependencies for extension modules and DLLs loaded with ctypes on Windows are now resolved more securely. Only the system paths, the directory containing the DLL or PYD file, and directories added with add_dll_directory() are searched for load-time dependencies. Specifically, PATH and the current working directory are no longer used, and modifications to these will no longer have any effect on normal DLL resolution.
Replacing `foo.dll` by a path `.\\foo.dll` is enough to fix this issue.
=> Fix dll not found on Python 3.8+

examples/tkvlc.py
Use `sys.base_prefix` if available inlieu of `sys.prefix` to find `libtk.dylib` on macOS in `venv`'s.
=> Fix for venv.

examples/tkvlc.py
Workaround as MacOS draws the video over the whole app including the buttons. Dividing the app into two seperate windows makes the app work as intended even on MacOS as the buttons stays visible.
Only tested on MacOS Mojave, version 10.14.6.
The _AnchorButtonsPanel is mainly for esthetic purposes, can be omitted.
=> TopLevel window to hold the buttons panel.

generator/generate.py
This PR proposes to fix a problem with return types for callbacks.
After commit c01a4f6523a1e03919ed3a34d3d0f231b010dab1, a problem arose with callbacks return types (in particular I found problem with `MediaOpenCb`, `MediaReadCb`, ...).
I'm missing the reason why all callback return types were forcefully converted to pointers (which is the main point of this PR).
Looking forward for any feedback.
=> fix return types for callbacks

examples/play_buffer.py
Close #88 
I wrote a basic script trying to show how to use callbacks. I know it's not the most basic example, but I thought it would have been useful for the final user for better understanding the mechanism.
Looking forward for your feedback on how to refine/improve it.
=> example usage of media callbacks

generator/templates/header.py, generator/templates/override.py
Proposing a new, internal function `len_args` to get the number of positional arguments of a callable.
This is to replace `inspect.getargspec` deprecated in Python 3 and `inspect.signature` not available in Python 2.
=> mrJean1 len_args

generator/generate.py
The "#define" regex does not seem to match empty value #define. For example, the "# define LIBVLC_API" line is not considered as define sequence. One of the consequence is the first function declaration detected is considered as part of a multiline block, and thus ignored.
Accepting "#define XXX" sequences as well as "#define XXX yyy" seems to fix the issue (first function declared in header missing).
=> generator: fix first function parse in header

examples/psgvlc.py
A new example using python-vlc with [PySimpleGUI](https://www.PySimpleGUI.org), modified from the latter's [Demo_Media_Player_VLC_Based.py](https://github.com/PySimpleGUI/PySimpleGUI/blob/master/DemoPrograms/Demo_Media_Player_VLC_Based.py) to work properly on macOS.
Note, `psgvlc.py` imports example [tkvlc.py](https://github.com/oaubert/python-vlc/blob/master/examples/tkvlc.py) to get to the macOS-specific functionality added since issue #194.
=> New example psgvlc.py

generator/templates/footer.py
Moved both functions `print_python` and `print_version` before `if __name__ == '__main__'.`  That way scripts like `examples/tkvlc.py -v` and `-/cocoavlc.py -v` will show all version information at once .
In addition, the Python line now includes the `platform.machine()` on macOS, important since the most recent macOS on Apple-Silicon.
=> Updated footer.py

examples/cocoavlc.py
[PyCocoa 21.11.02](https://github.com/mrJean1/PyCocoa) is required since that includes several updates to run on macOS 12.0.1 Monterey.
Added an attempt to force the video to fill the window, see this [PyCocoa issue](https://github.com/mrJean1/PyCocoa/issues/3).
=> 2 updates of cocoavlc.py

examples/tkvlc.py
Added a number of private classes to deal with `Tcl/Tk/tkinter` idiosyncrasies and differences on Windows and macOS.
On macOS, most `tkinter` calls seem delayed making it necessary to morph such calls into events (with `tkinter.after*` functions).
Changed the anchoring of the buttons and video panel by making both separate, movable windows.  Dragging and resizing each window now works smoothly and correctly on Windows and macOS.
Added menu options to change zoom, rate and opacity.  However, the zoom and rate items are disabled on macOS due to poor behavior (still unresolved).
=> Enhancements for Windows and macOS.

examples/tkvlc.py
Among a few other things, this version of `tkvlc.py` includes a workaround for a Tk issue on macOS: double events for accelerator keys defined with the `Shift` modifier.
For example, when using the `Cmd-Shift-+` key to `Zoom In`, two events are generated resulting in twice the zoom factor (with previous `tkvlc.py` versions).  Similarly for the `Cmd-Shift->` and `Cmd-Shift-<` keys to speed the video up or down.  Menu selections work fine.
The problem occurs only with recent Python releases on (recent) macOS versions and both on Intel and Apple Silicon.  An [issue has been](https://GitHub.com/python/cpython/issues/100588) submitted at the [Python GitHub](https://GitHub.com/python/cpython) site.
=> Double events.

generator/generate.py
I identified and fixed two bugs:
1. During bindings generation (`PythonGenerator.generate_funcs` and `PythonGenerator.generate_func_pointer_decorator`), `Func.docs_in_sphinx_format` was called _after_ `Par.flags`, when the former fills the `out` member of `Func`, which determines the output of `Par.flags`. This resulted in out parameters being ignored, even though they are properly gathered by `Func.docs_in_sphinx_format`. Actually, some are still taken into account, because in `Par.flags`, some pointer types are hard-coded to be considered out parameters (this hard-coding may not be necessary anymore).
This issue is fixed by commit "Partially fix regression in [OUT] parameter handling".
The functions concerned by the fix are:
- `libvlc_log_get_context`
- `libvlc_log_get_object`
2. …
=> Fix Regression in [OUT] parameters handling (Issue #287)
